# Generated by Django 4.2.7 on 2026-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_alter_menuitem_image_alter_outlet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
